from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status, Path
from sqlalchemy.orm import Session
from datetime import datetime

from ecore.auth.auth_handler import verify_token
from ecore.service.dependencies import get_db
from ecore.model.swap import Swap as DBSwap # Alias to avoid naming conflict with Pydantic Swap
from ecore.schema.swap_schema import SwapCreate, SwapResponse #SwapStatus # Pydantic models


# Create an API router for swap-related endpoints
swap_router = APIRouter(prefix="/swap", tags=["Swap"])


@swap_router.post(
    "/",
    response_model=SwapResponse, # Define the response model for automatic serialization and documentation
    status_code=status.HTTP_201_CREATED, # Set the HTTP status code for successful creation
    summary="Create a new swap",
    description="Creates a new swap entry in the database with the provided details."
)
async def create_swap(
    swap: SwapCreate,
    db: Session = Depends(get_db),
    token_payload: dict[str, Any] = Depends(verify_token)
):
    """
    Endpoint to create a new swap.

    - **swap**: The swap details to be created (id_item, id_user_giver, id_user_taker, optional date_swap, optional item_metadata).
    - **db**: The database session dependency.
    """
    # Create an instance of the SQLAlchemy ORM model from the Pydantic data
    # We explicitly set fields. If date_swap is not provided in the request,
    # the default (datetime.utcnow) from the SQLAlchemy model will be used.
    db_swap = DBSwap(
        id_item=swap.id_item,
        id_user_giver=swap.id_user_giver,
        id_user_taker=swap.id_user_taker,
        # Use the provided date_swap if it exists, otherwise the model's default will apply
        date_swap=swap.date_swap if swap.date_swap else datetime.utcnow(),
        item_metadata=swap.item_metadata  # Add this line
    )

    try:
        db.add(db_swap)    # Add the new object to the session
        db.commit()        # Commit the transaction to save the object to the database
        db.refresh(db_swap) # Refresh the object to populate id_swap (generated by DB) and any other defaults
        return db_swap     # Return the created object, FastAPI will convert it to SwapResponse
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Could not create swap: {e}"
        )


# --- NEW API Endpoint for Item Count by User (Updated for string IDs) ---
@swap_router.get("/users/{user_id}/items_given_count/")
async def get_user_items_given_count(
    # user_id is now a string in the path
    user_id: str = Path(..., description="The ID (string) of the user whose items count is requested."),
    token_payload: dict[str, Any] = Depends(verify_token),
    db: Session = Depends(get_db)
):


    # Query the database to count items owned by the specified user_id (string comparison)
    item_count = db.execute(
        """
        SELECT COUNT(*)
        FROM swap
        WHERE id_user_giver = :user_id
        """,
        {"user_id": user_id}
    ).fetchone()[0]

    # User existence check (string comparison)

    return {
        "user_id": user_id,
        "items_given_count": item_count
    }